name: Py-Packager - Deploy

on:
  push:
    branches:
      - feature/init

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Twine
      run: pip install twine
      working-directory: .

    - name: Build Distribution
      run: python setup.py sdist
      working-directory: .

    - name: Publish package
      run: twine upload --repository testpypi dist/* --non-interactive
      working-directory: .

